### ISSUE TITLE
EA - Error when getting data

### ISSUE THREAD

**Issue by marcgarraway** [Microsoft/peek#34]
Hi,
I have successfully deployed the application and it start collecting data, however, when it is looping through the monthly report for the EA, it gets to 2015-11 and throws the following error:

One or more errors occurred.
InnerException :
Exception of type 'Microsoft.Rest.HttpOperationException`1[System.Object]' was thrown.
StackTrace :
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at System.Threading.Tasks.Task`1.get_Result()
   at BillingWebJob.Helpers.EaDataHelper.GetFilteredEaBillingDataFromApi(String date)
   at BillingWebJob.Helpers.EaDataHelper.StartEaRoutine(Int32& status, Int32& totalRecordsCount, String& blobStorageUri)
   at BillingWebJob.Program.CronJob(TimerInfo timer)

Any idea how to get around `this?```

**Comment by s3banerjee** [comment]
Same Error , i ' m also getting

**Comment by s3banerjee** [comment]
Just to add we are doing for CSP and not EA or Direct.

**Comment by s3banerjee** [comment]
Marcgarraway , is your issue resolved with latest fix ?
