### ISSUE TITLE
EA usage error: The wait operation timed out

### ISSUE THREAD

**Issue by MathijsHofkens** [Microsoft/peek#44]
Hi, i'm experiencing an error while fetching the EA logs. CSP logs are working fine. The swagger API is also working for both EA/CSP. I already deployed the ASYNC version to check if this solves anything at all, but unfortunately it does not.

> [05/09/2017 14:56:51 > 94928d: INFO] Error encountered: 
[05/09/2017 14:56:51 > 94928d: INFO] An error occurred while executing the command definition. See the inner exception for details.
[05/09/2017 14:56:51 > 94928d: INFO] InnerException :
[05/09/2017 14:56:51 > 94928d: INFO] Execution Timeout Expired.  The timeout period elapsed prior to completion of the operation or the server is not responding.
[05/09/2017 14:56:51 > 94928d: INFO] InnerException :
[05/09/2017 14:56:51 > 94928d: INFO] The wait operation timed out
[05/09/2017 14:56:51 > 94928d: INFO] StackTrace :
[05/09/2017 14:56:51 > 94928d: INFO]    at System.Data.Entity.Core.EntityClient.Internal.EntityCommandDefinition.ExecuteStoreCommands(EntityCommand entityCommand, CommandBehavior behavior)
[05/09/2017 14:56:51 > 94928d: INFO]    at System.Data.Entity.Core.Objects.Internal.ObjectQueryExecutionPlan.Execute[TResultType](ObjectContext context, ObjectParameterCollection parameterValues)
[05/09/2017 14:56:51 > 94928d: INFO]    at System.Data.Entity.Core.Objects.ObjectQuery`1.<>c__DisplayClass7.<GetResults>b__6()
[05/09/2017 14:56:51 > 94928d: INFO]    at System.Data.Entity.Core.Objects.ObjectContext.ExecuteInTransaction[T](Func`1 func, IDbExecutionStrategy executionStrategy, Boolean startLocalTransaction, Boolean releaseConnectionOnSuccess)
[05/09/2017 14:56:51 > 94928d: INFO]    at System.Data.Entity.Core.Objects.ObjectQuery`1.<>c__DisplayClass7.<GetResults>b__5()
[05/09/2017 14:56:51 > 94928d: INFO]    at System.Data.Entity.SqlServer.DefaultSqlExecutionStrategy.Execute[TResult](Func`1 operation)
[05/09/2017 14:56:51 > 94928d: INFO]    at System.Data.Entity.Core.Objects.ObjectQuery`1.GetResults(Nullable`1 forMergeOption)
[05/09/2017 14:56:51 > 94928d: INFO]    at System.Data.Entity.Core.Objects.ObjectQuery`1.<System.Collections.Generic.IEnumerable<T>.GetEnumerator>b__0()
[05/09/2017 14:56:51 > 94928d: INFO]    at System.Data.Entity.Internal.LazyEnumerator`1.MoveNext()
[05/09/2017 14:56:51 > 94928d: INFO]    at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
[05/09/2017 14:56:51 > 94928d: INFO]    at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
[05/09/2017 14:56:51 > 94928d: INFO]    at BillingWebJob.Helpers.EaDataHelper.GetFilteredEaBillingDataFromApi(String date) in C:\Users\mhkbc67\stack\Work\Realdolmen\Internal projects\Peek\peek-master\AzureBillingAnalytics\BillingWebJob\Helpers\EaDataHelper.cs:line 216
[05/09/2017 14:56:51 > 94928d: INFO]    at BillingWebJob.Helpers.EaDataHelper.StartEaRoutine(Int32& status, Int32& totalRecordsCount, String& blobStorageUri) in C:\Users\mhkbc67\stack\Work\Realdolmen\Internal projects\Peek\peek-master\AzureBillingAnalytics\BillingWebJob\Helpers\EaDataHelper.cs:line 79
[05/09/2017 14:56:51 > 94928d: INFO]    at BillingWebJob.Program.CronJob(TimerInfo timer) in C:\Users\mhkbc67\stack\Work\Realdolmen\Internal projects\Peek\peek-master\AzureBillingAnalytics\BillingWebJob\Program.cs:line 140 

>

**Comment by MathijsHofkens** [comment]
Flushing the database and defining a shorter range for the data fixed this issue.

**Comment by BarisEris** [comment]
Mathijs, for others benefit; would you be so kind to state what specific range worked for you and what range failed?
