### ISSUE TITLE
Timeout for CspUtilization

### ISSUE THREAD

**Issue by townendk** [Microsoft/peek#49]
Hello, I'm currently using the implimentUtilization branch for my deployment and I am unable to retrieve the CspUtilization data, critically the resource tags which are my entire requirement for setting up Peek!

Whilst checking my API manually on the /swagger page I can retrieve results on each GET, with the exception of the CSPUtilization GET which eventually reports back:

<html><head><title>500 - The request timed out.</title></head><body>  <font color ="#aa0000">         <h2>500 - The request timed out.</h2></font>  The web server failed to respond within the specified time.</body></html>

Is this a known issue, or something limited to my deployment/implementation?

I'd appreciate any advice or remedy.

Regards,

**Comment by g00li3** [comment]
Good day.
I have the same issue.
All work except csputilization.

Please advise.

Miguel Silva

**Comment by g00li3** [comment]
Good day.
So after looking at the error message in the webjob and adding the necessary info at:

I was able to go to another error:

[07/19/2017 07:07:18 > d7c928: INFO] Now fetching utilization records from the Partner Center SDK.
[07/19/2017 07:07:18 > d7c928: INFO] 
[07/19/2017 07:07:18 > d7c928: INFO] Error encountered: 
[07/19/2017 07:07:18 > d7c928: INFO] Could not find file 'D:\local\Temp\jobs\continuous\BillingWebJob\4koaloog.3uj\ResourceUtilizationList.json'.
[07/19/2017 07:07:18 > d7c928: INFO] StackTrace :
[07/19/2017 07:07:18 > d7c928: INFO]    at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
[07/19/2017 07:07:18 > d7c928: INFO]    at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
[07/19/2017 07:07:18 > d7c928: INFO]    at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
[07/19/2017 07:07:18 > d7c928: INFO]    at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
[07/19/2017 07:07:18 > d7c928: INFO]    at System.IO.File.InternalReadAllText(String path, Encoding encoding, Boolean checkHost)
[07/19/2017 07:07:18 > d7c928: INFO]    at System.IO.File.ReadAllText(String path)

Please advise.

Miguel Silva

**Comment by MathijsHofkens** [comment]
@g00li3 did you solve this issue? I'm facing the exact same issue.
