### ISSUE TITLE
Anyone still using this code ? 

### ISSUE THREAD

**Issue by mullermand** [Microsoft/peek#52]
Hi
Is this code still working ?
I tried to build/use it, but get this error: 
[03/05/2019 14:52:33 > 206484: INFO] Starting CSP Routine. Current Usage, Historic Usage and Historic Billing data will be updated.. 
[03/05/2019 14:52:33 > 206484: INFO] 
[03/05/2019 14:52:33 > 206484: INFO] Fetching records for Current Month's Usage from the API. This may take a while. If this operation is timimg out, consider increasing the TimeOut limit in Configuration file. 
[03/05/2019 15:08:13 > 206484: INFO] 
[03/05/2019 15:08:13 > 206484: INFO] Error encountered: 
[03/05/2019 15:08:13 > 206484: INFO] One or more errors occurred.
[03/05/2019 15:08:14 > 206484: INFO] InnerException :
[03/05/2019 15:08:14 > 206484: INFO] Operation returned an invalid status code 'InternalServerError'
[03/05/2019 15:08:14 > 206484: INFO] StackTrace :
[03/05/2019 15:08:14 > 206484: INFO]    at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
[03/05/2019 15:08:14 > 206484: INFO]    at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
[03/05/2019 15:08:14 > 206484: INFO]    at System.Threading.Tasks.Task`1.get_Result()
[03/05/2019 15:08:14 > 206484: INFO]    at BillingWebJob.Helpers.CspDataHelper.StartCspRoutine(Int32& status, Int32& totalRecordsCount, String& blobStorageUri) in C:\Users\mlh\Desktop\Azure PEEK\peek-master\AzureBillingAnalytics\BillingWebJob\Helpers\CspDataHelper.cs:line 534
[03/05/2019 15:08:14 > 206484: INFO]    at BillingWebJob.Program.CronJob(TimerInfo timer) in C:\Users\mlh\Desktop\Azure PEEK\peek-master\AzureBillingAnalytics\BillingWebJob\Program.cs:line 122 
[03/05/2019 15:08:14 > 206484: INFO] 
[03/05/2019 15:08:14 > 206484: INFO] Adding audit information in AuditData table..
[03/05/2019 15:08:14 > 206484: INFO] 

And im not sure, if it is because the solution is unsupported ?

/Martin

**Comment by aldialynas** [comment]
Did you find a solution to this? I am getting the same error, but status code is "Forbidden". Would love some help on that.

**Comment by mullermand** [comment]
Nope, i gave up, think the code is way to old, and not supported anymore :(
